version: "2.2" 


services:
  resolver:
    build:
      context: ./resolver
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 176.96.4.1
    container_name: resolver

  soa_interne:
    build:
      context: ./soa_interne
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 176.96.4.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    container_name: soa_interne

  intranet:
    build:
      context: ./intranet
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 176.96.1.1
    ports:
      - "8080:80"
    container_name: intranet

  samba:
    build:
      context: ./samba
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 176.96.5.0
    ports:
      - "139:139"
    container_name: samba

  direction:
    build:
      context: ./user/direction
      dockerfile: Dockerfile
    networks:
      direction_network:
        ipv4_address: 176.96.1.1
    container_name: direction

  atelier:
    build:
      context: ./user/atelier
      dockerfile: Dockerfile
    networks:
      atelier_network:
        ipv4_address: 176.96.2.1
    container_name: atelier

  compta:
    build:
      context: ./user/compta
      dockerfile: Dockerfile
    networks:
      compta_network:
        ipv4_address: 176.96.3.1
    container_name: compta

  commerciaux:
    build:
      context: ./user/commerciaux
      dockerfile: Dockerfile
    networks:
      commerciaux_network:
        ipv4_address: 176.96.3.3
    container_name: commerciaux

  secretariat:
    build:
      context: ./user/secretariat
      dockerfile: Dockerfile
    networks:
      secretaire_network:
        ipv4_address: 176.96.1.2
    container_name: secretaire

networks:
  interne:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.96.4.0/24
          
  Direction:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.96.1.0/24
          gateway: 176.96.1.1
  Atelier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.96.2.0/24
          gateway: 176.96.2.1
  compta_network:
   driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.96.3.0/24
          gateway: 176.96.3.1
  commerciaux_network:
  driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.96.3.0/24
          gateway: 176.96.3.3
  secretaire_network:
   driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.96.1.0/24
          gateway: 176.96.1.2
