version : '3.6'

services :
  Directeur:
    image: posteuserinterne:latest 
    container_name: Directeur
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Direction:
        ipv4_address: 176.96.1.1

  Secretaire:
    image: posteuserinterne:latest
    container_name: Secretaire
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Direction:
        ipv4_address: 176.96.1.2

  comptable1:
    image: posteuserinterne:latest
    container_name: comptable1
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 176.96.3.1

  comptable2:
    image: posteuserinterne:latest
    container_name: comptable2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 176.96.3.2

  Commercial1:
    image: posteuserinterne:latest
    container_name: Commercial1
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 176.96.3.3

  Commercial2:
    image: posteuserinterne:latest
    container_name: Commercial2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 176.96.3.4

  Atelier1:
    image: posteuserinterne:latest
    container_name: Atelier1
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Atelier:
        ipv4_address: 176.96.2.1

  Atelier2:
    image: posteuserinterne:latest
    container_name: Atelier2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Atelier:
        ipv4_address: 176.96.2.2

networks:
  Direction:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.96.1.0/24
  Administration:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.96.3.0/24
  Atelier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.96.2.0/24
